apiVersion: v1
kind: Secret
metadata:
  name: workeracoes-secret
type: Opaque
data:
  RedisConnection: Z3JvZmZlY2FjaGUucmVkaXMuY2FjaGUud2luZG93cy5uZXQ6NjM4MCxwYXNzd29yZD15eHh1cnhiSXNHbWlHZGlZYlRicDNqSnlrT3hiSVdlUVRBekNhTlAxN1owPSxzc2w9VHJ1ZSxhYm9ydENvbm5lY3Q9RmFsc2U=
  KafkaBroker: Z3JvZmZlZXZlbnRodWJzLnNlcnZpY2VidXMud2luZG93cy5uZXQ6OTA5Mw==
  KafkaUsername: JENvbm5lY3Rpb25TdHJpbmc=
  KafkaPassword: RW5kcG9pbnQ9c2I6Ly9ncm9mZmVldmVudGh1YnMuc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1Sb290TWFuYWdlU2hhcmVkQWNjZXNzS2V5O1NoYXJlZEFjY2Vzc0tleT0vUEJyUnRFUERRcGRGVkowcld1S3dwTGc4NTdKZEpIRUpRMFJ1dkhXWmp3PQ==